version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_HOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  upload_download:
    image: ${DOCKER_USERNAME}/upload-download-service:latest
    container_name: upload-download-service-container
    ports:
      - "3100:3100"
    environment:
      APP_CLIENT: ${APP_CLIENT}
      APP_PORT: ${APP_PORT}
      APP_NAME: ${APP_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  rabbitmq_data:
